# Generated by Django 5.2.4 on 2025-09-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in_progress', 'В сборке'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default='accepted', max_length=50, verbose_name='Статус'),
        ),
    ]
