# Generated by Django 5.2.4 on 2025-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('online', 'Электронно')], db_index=True, default='cash', max_length=30, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
